version: build{build}

os: Visual Studio 2015
configuration: Release

# build
branches:
  only:
    - master

build: 
  project: StuntCarRacer_2008.sln
  verbosity: normal

artifacts:
  - path: Release\StuntCarRacer.exe

deploy:
  skip_tags: true
  description: Windows build
  provider: GitHub
  auth_token:
    secure: M9xvUw78oWu2qIEvVQ7bYKIfSrIDO4twEjWq3yaR8JVKcI4uUPAMfJuITLI+AfCS
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true