version: build{build}

os: Visual Studio 2015
configuration: Release

# build
branches:
  only:
    - master

build: 
  project: StuntCarRacer_2008.sln
  verbosity: normal

deploy:
  provider: GitHub
  auth_token:
    secure: M9xvUw78oWu2qIEvVQ7bYKIfSrIDO4twEjWq3yaR8JVKcI4uUPAMfJuITLI+AfCS
  artifact: C:\projects\stuntcarremake\Release\StuntCarRacer.exe
  draft: true
  prerelease: false
  force_update: true
  on:
    branch: master
