language: cpp
sudo: true
dist: trusty

compiler:
    - g++

#Build steps
before_install:
    - sudo apt-get install libsdl-mixer1.2-dev libsdl-image1.2-dev libsdl-ttf2.0-dev libopenal-dev libglm-dev -y

script: make LINUX=1

after_success:
  - mkdir out
  - mkdir out/bin
  - mkdir out/lib
  - cp stuntcarracer out/bin/
  - cp -r Bitmap out/bin/
  - cp -r Sounds out/bin/
  - cp -r Trackes out/bin/
  - mkdir -p out/share/applications
  - cp stuncarracer.desktop out/share/applications/
  - mkdir -p out/share/icons/hicolor/48x48
  - cp icon48.png out/share/icons/hicolor/48x48/stuntcarracer.png
  - mkdir -p out/share/icons/hicolor/96x96
  - cp icon.png out/share/icons/hicolor/48x48/stuntcarracer.png
  - mkdir -p out/share/icons/hicolor/256x256
  - cp icon256.png out/share/icons/hicolor/48x48/stuntcarracer.png
  - ls -lh out/*
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh out/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
